<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Filter</name>
   <tag></tag>
   <elementGuidId>f10b5daf-9a35-4b7e-b65a-17613782b521</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[normalize-space()='Filter']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[normalize-space()='Filter']</value>
      <webElementGuid>b11ca356-e136-4fed-a145-8cc527307870</webElementGuid>
   </webElementProperties>
</WebElementEntity>
