<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Filter_bar</name>
   <tag></tag>
   <elementGuidId>046d39dd-bc23-469e-9d7b-c27a5a78161f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[@name='status']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select[@name='status']</value>
      <webElementGuid>10c99f7f-7b5b-4eac-beb1-7b86f2f037b8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
