<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>List_Button_Detail</name>
   <tag></tag>
   <elementGuidId>74151e0c-7fb1-4718-97eb-82677385eb83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//tbody/tr/td[10]/a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//tbody/tr/td[10]/a[1]</value>
      <webElementGuid>45dd8e4f-2348-4f1a-b591-7220097bcc2e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
