<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>paging_Second</name>
   <tag></tag>
   <elementGuidId>a52b51af-1264-4c16-ad96-403561f0bd46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[normalize-space()='2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[normalize-space()='2']</value>
      <webElementGuid>e8c94cd7-51bf-4a7c-9f6c-f4ec7d84f24b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
