<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>paging_Third</name>
   <tag></tag>
   <elementGuidId>df8644c1-6f80-4b79-9d4b-3bab1ddee042</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[normalize-space()='3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[normalize-space()='3']</value>
      <webElementGuid>9442b1f5-710e-4c60-95f0-e39b52a30280</webElementGuid>
   </webElementProperties>
</WebElementEntity>
