<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>paging_First</name>
   <tag></tag>
   <elementGuidId>6c5345bb-7c15-4e73-9d43-276fe68bb01b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[normalize-space()='1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[normalize-space()='1']</value>
      <webElementGuid>e446900e-3c43-4789-b264-72708e90a157</webElementGuid>
   </webElementProperties>
</WebElementEntity>
