<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Table_OrderRows</name>
   <tag></tag>
   <elementGuidId>92a3aa45-b6eb-4518-b2b6-9a69cc333103</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//tbody/tr</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//tbody/tr</value>
      <webElementGuid>76ea82c3-121d-47a4-943f-ef6a33846521</webElementGuid>
   </webElementProperties>
</WebElementEntity>
