<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>product_detail_info_tittle_author</name>
   <tag></tag>
   <elementGuidId>3a29c4f6-19cc-4e83-9c76-ec64f64fd9ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;nav-details&quot;]/table/tbody/tr[2]/th</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;nav-details&quot;]/table/tbody/tr[2]/th</value>
      <webElementGuid>39762776-cf8c-4295-8ddc-b0486057aa85</webElementGuid>
   </webElementProperties>
</WebElementEntity>
