<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>product_detail_image</name>
   <tag></tag>
   <elementGuidId>317737e4-172f-47cb-a77d-131237820a8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//img[@class='product-details-img']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//img[@class='product-details-img']</value>
      <webElementGuid>9798ef5c-7720-4677-90f6-580b5df784e2</webElementGuid>
   </webElementProperties>
</WebElementEntity>
