<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_Submit_Response</name>
   <tag></tag>
   <elementGuidId>d69b8e32-379b-4c39-8084-3d23da9ab090</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[normalize-space()='Submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[normalize-space()='Submit']</value>
      <webElementGuid>ac91365f-3f72-48a5-92c4-d989160b4c39</webElementGuid>
   </webElementProperties>
</WebElementEntity>
