<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_Contact</name>
   <tag></tag>
   <elementGuidId>f5028de7-4866-44e4-8cb3-a06d74df9356</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;sidenavAccordion&quot;]/div[1]/div/a[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;sidenavAccordion&quot;]/div[1]/div/a[6]</value>
      <webElementGuid>075ceaab-1f31-4523-bb8d-f50790d28602</webElementGuid>
   </webElementProperties>
</WebElementEntity>
