<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Dropdown_SortBy</name>
   <tag></tag>
   <elementGuidId>b64e6c10-968b-4558-81b7-cd284f479f0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[@id='sortFilter']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select[@id='sortFilter']</value>
      <webElementGuid>b8da7d56-8570-44e0-b906-a03bb1778454</webElementGuid>
   </webElementProperties>
</WebElementEntity>
