<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_Response_Title</name>
   <tag></tag>
   <elementGuidId>30f27e66-a456-44f4-b957-178ac1c5273a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='categoryName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='categoryName']</value>
      <webElementGuid>d26e0067-bb4a-4a98-b73c-80082fff121d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
