<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_Response_Content</name>
   <tag></tag>
   <elementGuidId>a2beb1e9-b3fe-4ba8-a387-ce814c7f67a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//textarea[@id='description']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//textarea[@id='description']</value>
      <webElementGuid>fd88559c-628c-4d92-8f26-ed4c67b04306</webElementGuid>
   </webElementProperties>
</WebElementEntity>
