<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Msg_Contact</name>
   <tag></tag>
   <elementGuidId>8600b6ec-89bd-4490-868d-d2e7ace17816</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@role='alert']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@role='alert']</value>
      <webElementGuid>e29df2ce-d003-46f8-ac28-f861f73f283e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
