<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>table_ProductRows</name>
   <tag></tag>
   <elementGuidId>21c0fcf2-b7f7-4593-860b-5a22c7251bb8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//tbody/tr</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//tbody/tr</value>
      <webElementGuid>072295b4-9dfb-4684-900a-49ebe047c9b1</webElementGuid>
   </webElementProperties>
</WebElementEntity>
