<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_category_preview</name>
   <tag></tag>
   <elementGuidId>f405ab2d-d93e-4e62-b76c-de6cef144cd3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//body[1]/div[1]/section[1]/div[1]/div[2]/div[2]/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//body[1]/div[1]/section[1]/div[1]/div[2]/div[2]/div[1]</value>
      <webElementGuid>54693cd8-b523-48af-8003-4dba0095a25f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
