<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon_cart</name>
   <tag></tag>
   <elementGuidId>5e21d345-8093-4145-af9e-c89613aa4327</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@href='/cart']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@href='/cart']</value>
      <webElementGuid>6ad95e56-25a9-4696-b50f-78d422b9958d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
