<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon_Accounts</name>
   <tag></tag>
   <elementGuidId>ed2d5618-edb2-40fb-b672-74999d325811</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@class='setting__active']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@class='setting__active']</value>
      <webElementGuid>6617f6c7-246e-4745-9b46-0e429e3033b2</webElementGuid>
   </webElementProperties>
</WebElementEntity>
