<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Keyword</name>
   <tag></tag>
   <elementGuidId>44b4ec39-e7a3-42f1-9eae-2bea39ddb94e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='keyword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='keyword']</value>
      <webElementGuid>4b0b2929-42b2-4701-bb70-d0630c0832af</webElementGuid>
   </webElementProperties>
</WebElementEntity>
