<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_Summary</name>
   <tag></tag>
   <elementGuidId>a5e0062d-cd82-4332-84ad-3a8e4893779a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='summary']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='summary']</value>
      <webElementGuid>b16873ae-fefa-4142-b131-70523d292be9</webElementGuid>
   </webElementProperties>
</WebElementEntity>
