<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>List_Button_Delete</name>
   <tag></tag>
   <elementGuidId>8ea8b073-945f-4878-95eb-40794f547a18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//button[@type='button'][normalize-space()='Xóa'])</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//button[@type='button'][normalize-space()='Xóa'])</value>
      <webElementGuid>dabf9a91-2c94-4e5e-9e42-f028c510e3b7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
