<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>List_Post_Title</name>
   <tag></tag>
   <elementGuidId>4318878c-843a-4991-b760-6c62b800aaf5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//tbody/tr/td[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//tbody/tr/td[2]</value>
      <webElementGuid>413c51ba-8516-43a7-baa5-1fe804625922</webElementGuid>
   </webElementProperties>
</WebElementEntity>
