<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>//a[@id='readButton']</description>
   <name>Button_ReadDescription</name>
   <tag></tag>
   <elementGuidId>42cbdfc3-260d-4c33-a478-caa552b461ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='readButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
