<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>//div[@id='product-modal']//h1[@id='modal-book-title']</description>
   <name>Modal_BookTitle</name>
   <tag></tag>
   <elementGuidId>98b38d2f-3938-40e2-9980-b373c1e90501</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='product-modal']//h1[@id='modal-book-title']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
