<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_Update</name>
   <tag></tag>
   <elementGuidId>b7cf2131-1022-47ec-afbc-bb94095193f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[normalize-space()='Submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[normalize-space()='Submit']</value>
      <webElementGuid>41e8e139-3dcd-4540-b684-f3044fefee11</webElementGuid>
   </webElementProperties>
</WebElementEntity>
