<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>List_Category_Desc</name>
   <tag></tag>
   <elementGuidId>f610127a-7078-46a0-8e18-dbce93ff8ac0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//tbody/tr/td[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//tbody/tr/td[3]</value>
      <webElementGuid>8bba077f-46ef-4b7a-a7df-c3d2fd0be9fd</webElementGuid>
   </webElementProperties>
</WebElementEntity>
