<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>List_Category_Name</name>
   <tag></tag>
   <elementGuidId>1b725aca-8521-4b0c-b881-4356e5e1b238</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//tbody/tr/td[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//tbody/tr/td[2]</value>
      <webElementGuid>ab5592b6-525f-4a02-9109-189a294031e9</webElementGuid>
   </webElementProperties>
</WebElementEntity>
