<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Paging_Second</name>
   <tag></tag>
   <elementGuidId>279452d9-1bd5-402e-84e0-fe8b32b9e4fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[normalize-space()='2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[normalize-space()='2']</value>
      <webElementGuid>ed0a52ea-54fe-4f00-b3de-766b2541eb8e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
