<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Popup_Delete_Cancel</name>
   <tag></tag>
   <elementGuidId>44f936a5-cdfc-41dd-9b53-de67e1a6030a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[contains(text(),'Hủy')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[contains(text(),'Hủy')]</value>
      <webElementGuid>c451419d-106e-42db-9541-f28ba95adcda</webElementGuid>
   </webElementProperties>
</WebElementEntity>
