<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Popup_Verify_Delete</name>
   <tag></tag>
   <elementGuidId>0ed956f9-82dc-4806-90a6-a2f634118bcb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='modal-content']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='modal-content']</value>
      <webElementGuid>2732b5bd-4570-4de6-9a50-b7cb910e7000</webElementGuid>
   </webElementProperties>
</WebElementEntity>
