<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>register_address</name>
   <tag></tag>
   <elementGuidId>7edaa0a7-e3d7-44e3-a5a3-dd68b891911c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='address']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='address']</value>
      <webElementGuid>60b4bd8e-af29-4331-839d-5f545a05ebb0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
