<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>register_email</name>
   <tag></tag>
   <elementGuidId>333d187e-9105-47fb-9a00-020b9ff06b95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='email']</value>
      <webElementGuid>c67b369e-0410-41a9-908d-bcc82b41ca0b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
