<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>register_name</name>
   <tag></tag>
   <elementGuidId>7f7fb9b4-07d8-480f-85b2-d7d4c9762f1b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='fullName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='fullName']</value>
      <webElementGuid>bad15460-a72a-4d23-b07c-ebdb869f64d3</webElementGuid>
   </webElementProperties>
</WebElementEntity>
