<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>wishlist_add_cart</name>
   <tag></tag>
   <elementGuidId>f1eb8b92-261f-4514-96cc-b11b138a4b12</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//tbody/tr/td[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//tbody/tr/td[5]</value>
      <webElementGuid>84197a78-bcd5-4272-b068-7ac9686d44af</webElementGuid>
   </webElementProperties>
</WebElementEntity>
