<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>wishlist_product_price</name>
   <tag></tag>
   <elementGuidId>0641e08f-5313-4f6d-85a9-75fe1f477a59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//tbody/tr/td[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//tbody/tr/td[3]</value>
      <webElementGuid>ec0ef335-5a64-402a-b4e0-e716c441787e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
