<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_User</name>
   <tag></tag>
   <elementGuidId>bc8ce25d-8921-485f-a378-bce9ecb0ebb2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;sidenavAccordion&quot;]/div[1]/div/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;sidenavAccordion&quot;]/div[1]/div/a[2]</value>
      <webElementGuid>7b0e2577-c12c-448d-b52f-ffba2309b088</webElementGuid>
   </webElementProperties>
</WebElementEntity>
