<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>List_User_Address</name>
   <tag></tag>
   <elementGuidId>56a96c77-51c5-4640-960e-9b1e633bcc76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//tbody/tr/td[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//tbody/tr/td[5]</value>
      <webElementGuid>bb8f43c0-6684-48bf-86d2-071e4a4101c3</webElementGuid>
   </webElementProperties>
</WebElementEntity>
