<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>List_User_Phone</name>
   <tag></tag>
   <elementGuidId>c43b35b0-950c-49b4-849c-7a1ebe62b834</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//tbody/tr/td[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//tbody/tr/td[4]</value>
      <webElementGuid>c263fd6b-5d53-4b52-8551-5fe1ef0b8b78</webElementGuid>
   </webElementProperties>
</WebElementEntity>
