<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>List_User_Name</name>
   <tag></tag>
   <elementGuidId>e8ad9521-d223-46c0-bdb9-f813bf6c62b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//tbody/tr/td[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//tbody/tr/td[3]</value>
      <webElementGuid>680cad80-a1a6-43a8-860b-722bd663dbf1</webElementGuid>
   </webElementProperties>
</WebElementEntity>
