<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>List_User_Email</name>
   <tag></tag>
   <elementGuidId>b3edfbad-2760-4d45-958b-f49a5949b343</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//tbody/tr/td[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//tbody/tr/td[2]</value>
      <webElementGuid>cf5b5b48-7cfc-469f-bdac-a3ac05d58922</webElementGuid>
   </webElementProperties>
</WebElementEntity>
