<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Detail_Code</name>
   <tag></tag>
   <elementGuidId>46c811d8-07a6-408c-9d19-10d221eaea8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;wrapper&quot;]/div[3]/div/div/div/div/div[1]/p[1]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;wrapper&quot;]/div[3]/div/div/div/div/div[1]/p[1]/span</value>
      <webElementGuid>c426ee7a-011f-4921-8359-5aee1d7cb946</webElementGuid>
   </webElementProperties>
</WebElementEntity>
