<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Detail_Payment</name>
   <tag></tag>
   <elementGuidId>df92a406-b422-4df2-94e8-598e7aa9682b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;wrapper&quot;]/div[3]/div/div/div/div/div[1]/p[7]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;wrapper&quot;]/div[3]/div/div/div/div/div[1]/p[7]/span</value>
      <webElementGuid>9231dbfb-6561-4eb7-91da-f0f6cb484fb6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
