<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Detail_Status</name>
   <tag></tag>
   <elementGuidId>2079d156-de9b-4b56-99fd-e9e4f89c3387</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;wrapper&quot;]/div[3]/div/div/div/div/div[1]/p[6]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;wrapper&quot;]/div[3]/div/div/div/div/div[1]/p[6]/span</value>
      <webElementGuid>241cd7cc-1711-4045-a6db-964e59426e80</webElementGuid>
   </webElementProperties>
</WebElementEntity>
