<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>order_addres</name>
   <tag></tag>
   <elementGuidId>67775dcc-3a52-4b80-af26-598c181573ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//textarea[@id='address']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//textarea[@id='address']</value>
      <webElementGuid>f3ef876c-c5d1-4aad-a2e2-023f12689475</webElementGuid>
   </webElementProperties>
</WebElementEntity>
