<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cart_product_name</name>
   <tag></tag>
   <elementGuidId>256566f5-f448-413d-863b-c7fcaa794694</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//td[@class='product-name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//td[@class='product-name']</value>
      <webElementGuid>bf735257-3062-4973-9c1f-6fab94cc0221</webElementGuid>
   </webElementProperties>
</WebElementEntity>
