<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>list_product_price</name>
   <tag></tag>
   <elementGuidId>63d3aeca-c5b3-47bd-92cc-d95bd08becc7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//tbody/tr/td[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//tbody/tr/td[3]</value>
      <webElementGuid>ed0c9f9e-c245-448d-9f84-78daea67441c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
