<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>list_product_name</name>
   <tag></tag>
   <elementGuidId>82a66c60-5cf4-4126-bccb-7188f86a1c89</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//tbody/tr/td[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//tbody/tr/td[2]</value>
      <webElementGuid>ceaf9902-32bf-406a-b24b-223dbef11f07</webElementGuid>
   </webElementProperties>
</WebElementEntity>
