<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Form_description</name>
   <tag></tag>
   <elementGuidId>5a94fbfd-c9de-4ffb-bd1e-02241537e3b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//textarea[@id='description']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//textarea[@id='description']</value>
      <webElementGuid>bbd799d9-04d8-4a59-9e77-0cb74555274d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
