<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Form_salePrice</name>
   <tag></tag>
   <elementGuidId>55fe8c6b-8e43-4a55-ae0d-14b6e5083716</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='salePrice']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='salePrice']</value>
      <webElementGuid>fcdb6e43-cff7-4cc0-9cae-d69c7b25a919</webElementGuid>
   </webElementProperties>
</WebElementEntity>
