<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Form_bookPublisher</name>
   <tag></tag>
   <elementGuidId>773bdff6-5e3e-4e24-8635-a21295d619cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='bookPublisher']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='bookPublisher']</value>
      <webElementGuid>b8613512-3052-476b-930a-c5f367881f5b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
