<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Form_bookAuthor</name>
   <tag></tag>
   <elementGuidId>2f5db8e4-5440-4e3b-ba2c-9084dfe9d4f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='bookAuthor']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='bookAuthor']</value>
      <webElementGuid>b9712fcf-d635-47b9-ad9e-4e63ae1c9fa5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
