<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Form_Title</name>
   <tag></tag>
   <elementGuidId>8c771d20-fce7-412a-bf0a-75aea038fb83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='bookTitle']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='bookTitle']</value>
      <webElementGuid>dac7832a-2fd6-46fd-a862-33122855be5b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
