<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Keyword</name>
   <tag></tag>
   <elementGuidId>30ebc525-15ff-426b-acd3-eb43a9e78d23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='keyword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='keyword']</value>
      <webElementGuid>2425687c-bfa0-469a-98b4-51aebe519c0f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
