<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Popup_btn_Cancel</name>
   <tag></tag>
   <elementGuidId>b3724b17-1ff3-4fe4-85ad-8667177df53a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[contains(text(),'Hủy')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[contains(text(),'Hủy')]</value>
      <webElementGuid>e393e1ad-10c0-479f-916d-300622c3375e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
