<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Popup_NotForSale_Confirm</name>
   <tag></tag>
   <elementGuidId>eed39002-083f-4b4b-b152-ade04d90668d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='modal-content']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='modal-content']</value>
      <webElementGuid>9c08fc17-4a6c-4607-b071-57eda5482a7b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
