<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_send_contact</name>
   <tag></tag>
   <elementGuidId>12f76574-6abd-4a61-86e5-a4ca7c7ac631</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[contains(text(),'Gửi')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[contains(text(),'Gửi')]</value>
      <webElementGuid>25803fe3-cd61-447a-9096-ea8c60fe265a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
