<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>contact_message</name>
   <tag></tag>
   <elementGuidId>dbbaa444-179d-4a5a-bd77-fe1471fa46b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@role='alert']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@role='alert']</value>
      <webElementGuid>7d49073e-b5af-4484-bec2-b678d3614ba0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
