<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textbox_fullname</name>
   <tag></tag>
   <elementGuidId>4265787d-6a0f-4e06-8aa9-188bdc92c510</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='fullname']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='fullname']</value>
      <webElementGuid>b2128cfb-bbd2-48e0-91d7-700d74b8748f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
