<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textbox_tittle</name>
   <tag></tag>
   <elementGuidId>b83e9589-324b-4cc3-aba2-4ab562b688a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='title']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='title']</value>
      <webElementGuid>035a0d25-d210-4124-9b1a-95a3b6ac25c4</webElementGuid>
   </webElementProperties>
</WebElementEntity>
