<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textbox_msg</name>
   <tag></tag>
   <elementGuidId>f7c68a1a-27ad-43b8-97f6-b752bde9860c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//textarea[@id='message']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//textarea[@id='message']</value>
      <webElementGuid>30a4b401-157d-4265-95f4-1d6c1007be04</webElementGuid>
   </webElementProperties>
</WebElementEntity>
