<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>wishlist_product_status</name>
   <tag></tag>
   <elementGuidId>ffa033b7-425c-4178-b8f9-8939c30e1e86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//tbody/tr/td[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//tbody/tr/td[4]</value>
      <webElementGuid>09e38046-69cc-4689-b3ba-c88c43e914a6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
