<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>wishlist_product_name</name>
   <tag></tag>
   <elementGuidId>0a15075e-0154-4600-a2db-85cde6493470</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//tbody/tr/td[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//tbody/tr/td[2]</value>
      <webElementGuid>b0d9ca94-fa02-4095-8641-7eb4b9896a31</webElementGuid>
   </webElementProperties>
</WebElementEntity>
